// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgR_mJy_csEL8xuF1R2sbW9KYfXOP7dP4',
    appId: '1:933021714823:web:dad6f9ef3e4ef64e6beb22',
    messagingSenderId: '933021714823',
    projectId: 'mykomikid',
    authDomain: 'mykomikid.firebaseapp.com',
    storageBucket: 'mykomikid.firebasestorage.app',
    measurementId: 'G-CYZTXLGZ9V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmWuF42h4xPQyzK0PyAPyD4OkZtG6kLvk',
    appId: '1:933021714823:android:12c52e3c41c917ea6beb22',
    messagingSenderId: '933021714823',
    projectId: 'mykomikid',
    storageBucket: 'mykomikid.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb2JLeTrvuxG53vhnlfPjYR5W_mJTMSuw',
    appId: '1:933021714823:ios:a4b33d526b8ef3cb6beb22',
    messagingSenderId: '933021714823',
    projectId: 'mykomikid',
    storageBucket: 'mykomikid.firebasestorage.app',
    iosClientId: '933021714823-k8q9t0kud5ks7k30qc6qm2e170f7j5m5.apps.googleusercontent.com',
    iosBundleId: 'com.example.myMangaReader',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCb2JLeTrvuxG53vhnlfPjYR5W_mJTMSuw',
    appId: '1:933021714823:ios:a4b33d526b8ef3cb6beb22',
    messagingSenderId: '933021714823',
    projectId: 'mykomikid',
    storageBucket: 'mykomikid.firebasestorage.app',
    iosClientId: '933021714823-k8q9t0kud5ks7k30qc6qm2e170f7j5m5.apps.googleusercontent.com',
    iosBundleId: 'com.example.myMangaReader',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgR_mJy_csEL8xuF1R2sbW9KYfXOP7dP4',
    appId: '1:933021714823:web:a200daf885f9f49a6beb22',
    messagingSenderId: '933021714823',
    projectId: 'mykomikid',
    authDomain: 'mykomikid.firebaseapp.com',
    storageBucket: 'mykomikid.firebasestorage.app',
    measurementId: 'G-93PM1WCF5P',
  );

}